language: python
python:
  - '3.6'

stages:
  - test
  - name: deploy
    if: (tag IS present) AND (repo = ridi/ridi-django-oauth2-resource)

jobs:
  include:
  - stage: test
    before_script: make install-dev
    script: make lint
    script: make test

  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: ridi
      password:
        secure: "fLVfcxZZcwwVWiNo8Cag4wZ69eRISyKmrSo03zQGlLekuPSwphpX+x3tPtCMRy30dxo2fL7aiLHUFLHTrn2sSBvKpfQkAWBHkb1mMS9QoKupef6hDvqSUEeAUSQI8QCxVQAWS7zjdrVWp8yC89is/qdyl4N7inhPmmQYWYqIix+ElLiyWxzviuRQWUGxYNzwnwh/NTCNnouvzD4aCXllOPhh/0o2zuaRrTbcri6NzgVMbLOYEjpgrQdEyoLQEmQQSagO3GamrUegtgNCrytXw7b4nwnS2RsJ2EFEgl/3Y2rbmzk+Oxm9ALjp8cNh93jtxnqYZnKdie41fdwFUxV1Y9o3MKOKv3R/yz6gt2kYKZAqhN91ZXQKBCcQxMgRT5nEHF8XgxkwB2VzXcGUaYcAvcDw2Bnp4I+aAlJJu81pmvbMU20k/49m1W+fROWFMAIqW7l6jzKLbnObZHVByBOBq5mq8Wo4Ar7dehAL31O1KgFjggG6kqsCkrw9EvPn+eKEA1Bq7VgZA6dHTq87clR8Q70tyPIu1kVlPlhGKpQT45eI/Pp2LTjLP7OwKO3OkGq7NgSJCUXCCbhVP4VWX2N8tmFS9vwqumcwMn480zH/QD24QM/tG+RDWm9XU+uJ4f5bSCMa2gA3JyyFllOl0isjLjJWkIYu/DpNDe7AH4Ng0bs="
      on:
        repo: ridi/ridi-django-oauth2-resource
        tags: true
