language: python
python:
  - '3.6'

stages:
  - test
  - name: deploy
    if: (tag IS present) AND (repo = ridi/django-oauth2)

jobs:
  include:
  - stage: test
    before_script: make install-dev
    script: make lint
    script: make test

  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: ridi
      password:
        secure: "XXYh4s2v5qq9XMowMKs3bLfnCWzZWiEuMea1IS1Po+lq8RJsHIRCheBmA0mcPFIRoC3+VOcrN0lstxdbWfp76JEjoO53278xU53ETYt7ncvHZ0fyFMb9aEFFi/qHQ6R+0O9RRzF9K+ArxvPQTT7MB5zyd87HxehF4pHm/PSgInoUyBNtHAPBkC3BMfbMPoWNHIgJzGnT00BACZfLCmxjkFChMoMoeiRrSuS6b6xE9B3t13OlntWtNt1OZgHKOlkcHNwsorrsI5Svmd5dpDLfyBse4kwjDrw6jgNoA80dw1GCPgtedrzFgfNsMmPMGWGyS64WLPS0YKtnXkThfGos/JUMObKCj9IFur/Ml6jMAVo8+j5WptGBJPOWKmbhiUClr1DuxILTj3Sk05cx0uiqFG43JFW+Ml43uosd7IpdcWA1/xnjE8qG42fkIZ0YXpdXR8cajjQ6FIOSq+qY5CChOgcgNEZZpNIJMaCIsSnmUPKDKnt4qSuahti++3JanKIWrW+m6bmsMWGLCgAFlUZl3ljSkHRZsT43ZfHf0h/Kktg7t3P+GJPpZYZtPtILXdNDs2H36fQYmgLswWQyoCu9hBGrYUUEdEuxCYxFecGNd+w7RIY6gAVAlqCIW7eVEi14uLmKMvzskQaPofq49Dw/7ZST9onumyLDk3NML30cIYg="
      on:
        repo: ridi/django-oauth2
        tags: true
